services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 8030:3000
    volumes:
      - dbgate-data:/root/.dbgate
    container_name: dbgate
    networks:
      - mysql57_net
      - postgres_net

volumes:
  dbgate-data:
    driver: local

networks:
  mysql57_net:
    external: true
  postgres_net:
    external: true
