services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 8030:3000
    volumes:
      - dbgate-data:/root/.dbgate
    container_name: dbgate
    networks:
      mysql57_net:
        ipv4_address: 10.6.0.3
      mysql8_net:
        ipv4_address: 10.7.0.3
      postgres_net:
        ipv4_address: 10.5.0.3
      web:
        ipv4_address: 172.18.0.5
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.dbgate.rule=Host(`dbgate.d.ulmo`)
      - traefik.http.routers.dbgate.entrypoints=https
      - traefik.http.routers.dbgate.tls=true
      - traefik.http.routers.dbgate.service=dbgate@docker
      - traefik.http.services.dbgate.loadbalancer.server.port=3000
volumes:
  dbgate-data:
    driver: local

networks:
  mysql57_net:
    external: true
  postgres_net:
    external: true
  mysql8_net:
    external: true
  web:
    external: true
