services:
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 8030:3000
    volumes:
      - dbgate-data:/root/.dbgate
    container_name: dbgate
    networks:
      - mysql57_default
      - postgres

volumes:
  dbgate-data:
    driver: local

networks:
  mysql57_default:
    external: true
  postgres:
    external: true
