services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dtdsv3010
    networks:
      - postgres

networks:
  postgres:
    external: true
